apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-operator
  namespace: tomcat-operator
spec:
  selector:
    matchLabels:
      app: tomcat-operator
  replicas: 1 # we always run a single replica of the operator to avoid duplicate handling of events
  strategy:
    type: Recreate # during an upgrade the operator will shut down before the new version comes up to prevent two instances running at the same time
  template:
    metadata:
      labels:
        app: tomcat-operator
    spec:
      serviceAccountName: myoperator # specify the ServiceAccount under which's RBAC persmissions the operator will be executed under
      containers:
      - name: operator
        image: ${DOCKER_REGISTRY}/{MYOPERATOR_IMAGE}:${MYOPERATOR_VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health # when this returns 200 the operator is considered up and running
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health # when this endpoint doesn't return 200 the operator is considered broken and get's restarted
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
